=== SanAndreaP/SanLib/dev/sanlib-gui-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/SanAndreasP/SanLib/1.12/dev/sanlib-gui-schema.json",
  "definitions": {
    "color": {
      "type": "string",
      "pattern": "^0x[0-9a-fA-F]{8}$"
    },
    "item": {
      "type": "object",
      "properties": {
        "item":  { "type": "string" },
        "count": { "type": "integer", "minimum": 1, "default": 1 },
        "data":  { "type": "integer", "minimum": 0, "maximum": 65535, "default": 0 },
        "nbt":   { "type": "object", "default": null }
      },
      "required": ["item"]
    },
    "element": {
      "type": "object",
      "properties": {
        "type":      { "type": "string" },
        "id":        { "type": "string", "default": null },
        "pos":       { "type": "array", "minItems": 2, "maxItems": 2, "items": { "type": "integer" }, "default": [0, 0] },
        "alignment": { "type": "array", "minItems": 1, "maxItems": 2, "items": { "type": "string", "enum": ["left", "center", "right", "justify", "top", "bottom"] }, "default": ["left", "top"] }
      },
      "allOf": [
        {
          "if":   { "properties": { "type": { "const": "button" } } },
          "then": { "properties": { "data": { "$ref": "schema/button.json#/definitions/data" } } }
        },
        {
          "if":   { "properties": { "type": { "pattern": "^(dynamic_text|container_name|rflux_text)$" } } },
          "then": { "properties": { "data": { "$ref": "schema/text_dyn.json#/definitions/data"} } }
        },
        {
          "if":   { "properties": { "type": { "const": "group_box" } } },
          "then": { "properties": { "data": { "$ref": "schema/group_box.json#/definitions/data"} } }
        },
        {
          "if":   { "properties": { "type": { "const": "item" } } },
          "then": { "properties": { "data": { "$ref": "schema/item.json#/definitions/data"} } }
        },
        {
          "if":   { "properties": { "type": { "const": "rectangle" } } },
          "then": { "properties": { "data": { "$ref": "schema/rectangle.json#/definitions/data"} } }
        },
        {
          "if":   { "properties": { "type": { "const": "scroll_area" } } },
          "then": { "properties": { "data": { "$ref": "schema/scroll_area.json#/definitions/data"} } }
        },
        {
          "if":   { "properties": { "type": { "const": "text" } } },
          "then": { "properties": { "data": { "$ref": "schema/text.json#/definitions/data" } } }
        },
        {
          "if":   { "properties": { "type": { "const": "textfield" } } },
          "then": { "properties": { "data": { "$ref": "schema/textfield.json#/definitions/data" } } }
        },
        {
          "if":   { "properties": { "type": { "pattern": "^(texture|rflux_bar)$" } } },
          "then": { "properties": { "data": { "$ref": "schema/texture.json#/definitions/data" } } }
        },
        {
          "if":   { "properties": { "type": { "const": "tooltip" } } },
          "then": { "properties": { "data": { "$ref": "schema/tooltip.json#/definitions/data" } } },
          "else": { "properties": { "data": { "type": "object", "default": {} } } }
        }
      ],
      "required": ["type"]
    },
    "elements": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/element"
      }
    }
  },
  "type": "object",
  "properties": {
    "width":   { "type": "integer", "minimum": 0, "default": 0 },
    "height":  { "type": "integer", "minimum": 0, "default": 0 },
    "texture": { "type": "string", "default": null },
    "parent":  { "type": "string", "default": null },
    "backgroundElements":   { "$ref": "#/definitions/elements" },
    "foregroundElements":   { "$ref": "#/definitions/elements" }
  },
  "required": ["backgroundElements", "foregroundElements"]
}

=== SanAndreaP/SanLib/src/main/resources/assets/test/guis/test.json
{
  "width": 176,
  "height": 166,
  "backgroundElements": [
    {
      "type": "texture",
      "x": 0,
      "y": 0,
      "data": {
        "size": [176, 166],
        "uv": [0, 0],
        "location": "textures/gui/container/inventory.png"
      }
    },
    {
      "type": "texture",
      "x": 2,
      "y": 2,
      "data": {
        "size": [176, 166],
        "uv": [0, 0],
        "scale": [0.5, 0.5],
        "location": "textures/gui/container/inventory.png"
      }
    }
  ],
  "foregroundElements": [
    {
      "type": "text",
      "x": 3,
      "y": 5,
      "data": {
        "color": "0xFFFF0000",
        "text": "sanlib.test.text"
      }
    },
    {
      "type": "rectangle",
      "x": 14,
      "y": 0,
      "data": {
        "width": 64,
        "height": 64,
        "colorStart": "0x80FF00FF",
        "colorEnd": "0x8000FFFF",
        "horizontal": false
      }
    }
  ]
}

=== SanAndreaP/SanLib/src/test/resources/assets/santest/guis/test.json
{
  "width": 195,
  "height": 136,
  "texture": "santest:guis/test.png",
  "backgroundElements": [
    {
      "type": "texture",
      "data": {
        "size": [195, 136],
        "uv": [0, 0]
      }
    },
    {
      "type": "button",
      "pos": [-50, 0],
      "data": {
        "size": [50, 60],
        "label": "testing\ntesting2"
      }
    },
    {
      "type": "group_box",
      "pos": [5, 5],
      "data": {
        "size": [186, 127],
        "title": {
          "text": "test"
        }
      }
    }
  ],
  "foregroundElements": [
    {
      "type": "tooltip",
      "pos": [0, 0],
      "data": {
        "size": [16, 16],
        "content": {
          "type": "text",
          "data": {
            "text": "Bedrock",
            "shadow": true,
            "color": "FFFFFF"
          }
        }
      }
    },
    {
      "type": "tooltip",
      "pos": [16, 0],
      "data": {
        "size": [16, 16],
        "content": {
          "type": "rectangle",
          "data": {
            "size": [10, 10],
            "color": ["0xFFFFFF00", "0xFFFF0000"]
          }
        }
      }
    },
    {
      "type": "_stack_panel",
      "pos": [8, 16],
      "data": {
        "content": [
          {
            "type": "rectangle",
            "data": {
              "size": [10, 10],
              "color": ["0xFF00FF00"]
            }
          },
          {
            "type": "stack_panel",
            "pos": [0, 0],
            "data": {
              "horizontal": true,
              "padding": [5],
              "content": [
                {
                  "type": "rectangle",
                  "data": {
                    "size": [35, 5],
                    "color": ["0xFFFFFF00"]
                  }
                },
                {
                  "type": "rectangle",
                  "data": {
                    "size": [15, 9],
                    "color": ["0xFFFF0000"]
                  }
                }
              ]
            }
          },
          {
            "type": "rectangle",
            "data": {
              "size": [10, 10],
              "color": ["0xFF0000FF"]
            }
          }
        ]
      }
    },
    {
      "type": "scroll_area",
      "pos": [9, 18],
      "data": {
        "rasterized": true,
        "areaSize": [160, 110],
        "scrollbarHeight": 110,
        "scrollbarPos": [175, 18],
        "scrollButton": {
            "size": [12, 15],
            "uv": [232, 0],
            "uvDisabled": [244, 0]
        },
        "elements": [
          {
            "type": "rectangle",
            "pos": [0, 0],
            "data": {
              "size": [100, 110],
              "color": ["0xFFFFFF00", "0xFFFF0000"]
            }
          },
          {
            "type": "rectangle",
            "pos": [0, 110],
            "data": {
              "size": [100, 110],
              "color": ["0xFF00FFFF", "0xFF0000FF"]
            }
          },
          {
            "type": "rectangle",
            "pos": [0, 220],
            "data": {
              "size": [100, 110],
              "color": ["0xFFFF00FF", "0xFF00FF00"]
            }
          }
        ]
      }
    }
  ]
}

=== SanAndreaP/SanLib/src/test/resources/assets/santest/lexicon/lexicon.json
{
  "width": 195,
  "height": 136,
  "texture": "santest:lexicon/test.png",
  "backgroundElements": [
    {
      "type": "texture",
      "pos": [0, 0],
      "data": {
        "size": [195, 136],
        "uv": [0, 0]
      }
    },{
      "type": "scroll_area",
      "pos": [9, 18],
	  "id": "contentPane",
      "data": {
        "areaSize": [160, 110],
        "scrollbarHeight": 110,
        "scrollbarPos": [175, 18],
        "scrollButton": {
            "size": [12, 15],
            "uv": [232, 0],
            "uvDisabled": [244, 0]
        },
        "elements": []
      }
    }
  ],
  "foregroundElements": []
}

=== SanAndreaP/SanLib/src/main/resources/assets/sanlib/guis/test.json
{
  "width": 176,
  "height": 166,
  "backgroundElements": [
    {
      "type": "texture",
      "x": 0,
      "y": 0,
      "data": {
        "width": 176,
        "height": 166,
        "u": 0,
        "v": 0,
        "location": "textures/gui/container/inventory.png"
      }
    }
  ],
  "foregroundElements": [
    {
      "type": "text",
      "x": 3,
      "y": 5,
      "data": {
        "color": "0xFFFF0000",
        "text": "sanlib.test.text"
      }
    },
    {
      "type": "rectangle",
      "x": 14,
      "y": 0,
      "data": {
        "width": 64,
        "height": 64,
        "colorStart": "0x80FF00FF",
        "colorEnd": "0x8000FFFF",
        "horizontal": false
      }
    }
  ]
}
